### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by junnac** [junnac/Brewer#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds
- [x] Users can sign up, sign in, log out
- [x] Users can use a demo login to try the site
- [x] Users are redirected from the home page to the login/signup page if they are not logged in.

**Comment by ryan-mapa** [comment]
Really nice job! :)

**Comment by junnac** [comment]
Thank you!!
